version: '3.8'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "./config:/mosquitto/config"
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
volumes:
  config:
  data:
  log:

networks:
    mosquitto:
        name: mosquitto
        driver: bridge
