version: '3.8'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "/home/umbrel/eclipse-mosquitto/config:/mosquitto/config"
      - "/home/umbrel/eclipse-mosquitto/data:/mosquitto/data"
      - "/home/umbrel/eclipse-mosquitto/log:/mosquitto/log"
      - "./config:/mosquitto/config"
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
