version: '3.7'

services:
  hyperion:
    image: foorschtbar/hyperion
    container_name: hyperion
    ports:
      - 8090:8090
      - 8091:8091
      - 19444:19444
      - 19445:19445
    volumes:
      - ${APP_DATA_DIR}/config/:/root/.hyperion
    restart: unless-stopped